### ISSUE TITLE
help

### ISSUE THREAD

**Issue by oskarkui** [SemmieDev/Disc-Jockey#7] opened 2023-03-31 17:24 UTC
![image](https://user-images.githubusercontent.com/128618582/229188520-87a12925-e5e4-4779-ba9b-c3d962b29246.png)

i have the same issue it is that the song wont load event for an hour and it never loads i tried takeing it out of the files but it didnt work so please i need help (ik i didnt reply to the other one bc i forgot)

**Comment by SemmieDev** [comment] 2023-06-12 18:48
Duplicate of #6

**Closed as completed by SemmieDev** 2023-06-12 18:48 UTC
